export const users = [
  { id: 1, name: "Taaha", email: "taaha@gmail.com" },
  { id: 2, name: "John", email: "john@gmail.com" },
  { id: 3, name: "Alice", email: "alice@gmail.com" },
  { id: 4, name: "Bob", email: "bob@gmail.com" },
  { id: 5, name: "Charlie", email: "charlie@gmail.com" },
  { id: 6, name: "David", email: "david@gmail.com" },
  { id: 7, name: "Emma", email: "emma@gmail.com" },
  { id: 8, name: "Frank", email: "frank@gmail.com" },
  { id: 9, name: "Grace", email: "grace@gmail.com" },
  { id: 10, name: "Henry", email: "henry@gmail.com" },
  { id: 11, name: "Isabella", email: "isabella@gmail.com" },
  { id: 12, name: "Jack", email: "jack@gmail.com" },
  { id: 13, name: "Kevin", email: "kevin@gmail.com" },
  { id: 14, name: "Lily", email: "lily@gmail.com" },
  { id: 15, name: "Mason", email: "mason@gmail.com" },
  { id: 16, name: "Nora", email: "nora@gmail.com" },
  { id: 17, name: "Oliver", email: "oliver@gmail.com" },
  { id: 18, name: "Penelope", email: "penelope@gmail.com" },
  { id: 19, name: "Ryan", email: "ryan@gmail.com" },
  { id: 20, name: "Sophia", email: "sophia@gmail.com" },
];
